// /services/paid-media/ — Brand v3 service detail.
//
// Implements the FINAL APPROVED design "Tilth Service - Paid Media.dc.html" per
// TILTH_PAID_MEDIA_HANDOFF.md.
// Markup, inline styles and copy are the approved design verbatim; the
// responsive layer lives in assets/service-detail.css (shared) plus
// assets/service-detail-paid.css (this page's ladders, the stacked hero, the
// service-architecture row and the COMPOUNDING LOOP), and the behaviour in
// service-detail.js.
//
// Bespoke rather than generated by templates/servicePage.mjs — the sixth page
// on the pattern performance-marketing.mjs, growth-strategy-measurement.mjs,
// seo-ai-search.mjs, affiliate-partnerships.mjs and website-service.mjs already
// use. Content still comes from serviceContent so SEO copy, FAQs and schema
// stay in one place.
//
// SEO, schema, breadcrumb and analytics are carried over from the generated
// page this replaces, unchanged.
import { site, services } from "../data.mjs";
import { serviceContent } from "../content.mjs";
import { breadcrumbs } from "../render.mjs";

const slug = "paid-media";
const path = `/services/${slug}/`;
const svc = services.find(s => s.slug === slug);
const c = serviceContent[slug];

const bc = breadcrumbs([
  { name: "Home", path: "/" },
  { name: "Services", path: "/services/" },
  { name: svc.name, path }
]);

// Schema is unchanged from the generated page it replaces — same Service,
// BreadcrumbList and FAQPage graph, built from the same approved content.
const serviceSchema = {
  "@type": "Service", name: svc.name, serviceType: svc.keyword,
  provider: { "@id": `${site.base}/#org` },
  areaServed: [{ "@type": "Country", name: "United States" }, { "@type": "Country", name: "India" }, "Worldwide"],
  description: svc.summary, url: site.base + path
};
const faqSchema = {
  "@type": "FAQPage",
  mainEntity: c.faqs.map(([q, a]) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } }))
};

const main = `
  <section id="hero" data-depth-label="SURFACE" style="padding:112px var(--pad) 0;background-image:linear-gradient(90deg,var(--grid) 1px,transparent 1px);background-size:calc(100%/6) 100%">
    <nav aria-label="Breadcrumb" style="font-family:'IBM Plex Mono',monospace;font-size:11px;letter-spacing:.14em;line-height:1.6;color:var(--stone);animation:gFade .8s ease both">
      <a href="/" style="color:var(--stone)">HOME</a> <span aria-hidden="true" style="color:var(--mosstext);padding:0 6px">/</span> <a href="/services/" style="color:var(--stone)">SERVICES</a> <span aria-hidden="true" style="color:var(--mosstext);padding:0 6px">/</span> <span style="color:var(--fg)">PAID MEDIA</span>
    </nav>

    <div data-hero-grid style="display:grid;align-items:start">
      <div>
        <div style="font-family:'IBM Plex Mono',monospace;font-size:11.5px;letter-spacing:.16em;line-height:1;color:var(--mosstext);margin-bottom:22px;animation:gFade .8s .05s ease both">PAID MEDIA</div>
        <h1 data-h1 data-fit style="margin:0;font-family:Syne,sans-serif;font-weight:800;font-size:var(--h1);line-height:.94;letter-spacing:-.045em;text-transform:uppercase;animation:gRise 1s cubic-bezier(.16,1,.3,1) both">Paid media that's built to <em style="font-style:normal;color:var(--mosstext)">compound</em>.</h1>
        <p data-hero-p style="margin:32px 0 0;font-size:var(--body);line-height:1.6;max-width:56ch;color:var(--stone);animation:gRise 1s .12s cubic-bezier(.16,1,.3,1) both">Google, Meta and LinkedIn campaigns structured around real conversions — so spend scales against verified results instead of vanity metrics.</p>
        <div data-hero-cta style="display:flex;margin-top:36px;animation:gRise 1s .2s cubic-bezier(.16,1,.3,1) both">
          <a data-herocta href="/contact/" style="display:inline-flex;align-items:center;justify-content:center;gap:10px;height:54px;padding:0 28px;background:var(--moss);color:#101310;font-family:Syne,sans-serif;font-weight:700;font-size:14.5px;text-transform:uppercase;line-height:1;white-space:nowrap;border-radius:2px">Discuss This Challenge <span aria-hidden="true">&rarr;</span></a>
          <a data-textcta href="/work/" data-secondary style="display:inline-flex;align-items:center;height:54px;font-size:14.5px;line-height:1;white-space:nowrap;color:var(--stone)"><span style="border-bottom:1px solid var(--line2);padding-bottom:3px">See our work &rarr;</span></a>
        </div>
      </div>

      <div data-heropos style="border:1px solid var(--line);padding:22px 22px 24px;animation:gFade 1s .3s ease both">
        <div style="font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.14em;line-height:1;color:var(--stone);padding-bottom:14px;border-bottom:1px solid var(--line)">POSITION IN THE GROWTH SYSTEM</div>
        <div data-rel style="display:grid;padding-top:18px">
          <div>
            <div style="font-family:Syne,sans-serif;font-weight:700;font-size:26px;letter-spacing:-.03em;line-height:1;text-transform:uppercase">Distribution</div>
            <div style="font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.14em;line-height:1;color:var(--mosstext);margin-top:10px">DEPTH &middot; SURFACE</div>
          </div>
          <div>
            <div style="font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.14em;line-height:1;color:var(--stone);margin-bottom:12px">CONNECTS WITH</div>
            <div style="display:flex;flex-direction:column">
              <a data-connk href="/services/performance-marketing/" style="display:flex;justify-content:space-between;align-items:baseline;gap:14px;padding:11px 0;border-top:1px solid var(--line);font-size:13.5px;line-height:1.35;color:var(--stone)">Performance Marketing <span aria-hidden="true" style="color:var(--mosstext)">&rarr;</span></a>
              <a data-connk href="/services/brand-creative/" style="display:flex;justify-content:space-between;align-items:baseline;gap:14px;padding:11px 0;border-top:1px solid var(--line);font-size:13.5px;line-height:1.35;color:var(--stone)">Brand Strategy &amp; Performance Creative <span aria-hidden="true" style="color:var(--mosstext)">&rarr;</span></a>
              <a data-connk href="/services/growth-strategy-measurement/" style="display:flex;justify-content:space-between;align-items:baseline;gap:14px;padding:11px 0;border-top:1px solid var(--line);border-bottom:1px solid var(--line);font-size:13.5px;line-height:1.35;color:var(--stone)">Growth Strategy &amp; Measurement <span aria-hidden="true" style="color:var(--mosstext)">&rarr;</span></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section id="problem" data-depth-label="SYMPTOM" style="padding:var(--sy) var(--pad) 0">
    <div class="v3-reveal" style="font-family:'IBM Plex Mono',monospace;font-size:11.5px;letter-spacing:.16em;line-height:1;color:var(--mosstext);margin-bottom:22px">THE PROBLEM</div>
    <div class="v3-reveal" data-prob-head style="display:flex;border-bottom:1px solid var(--line);padding-bottom:24px">
      <h2 data-h2 data-fit style="margin:0;font-family:Syne,sans-serif;font-weight:700;font-size:var(--h2);line-height:1.02;letter-spacing:-.035em;text-transform:uppercase">When campaigns run but don't compound.</h2>
      <p data-probhint style="margin:0;font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.14em;line-height:1.7;color:var(--stone);max-width:32ch">FIVE CONDITIONS WE LOOK FOR BEFORE INCREASING SPEND</p>
    </div>

    <div data-prob-list style="display:flex;flex-direction:column;margin-top:20px">
      <div class="v3-reveal" data-prow style="display:grid;align-items:baseline;padding:26px 0;border-bottom:1px solid var(--line)">
        <span style="font-family:'IBM Plex Mono',monospace;font-size:11px;letter-spacing:.12em;line-height:1;color:var(--mosstext)">01</span>
        <p style="margin:0;font-size:var(--body);line-height:1.55;color:var(--fg);max-width:46ch">Account structure is messy and hard to scale.</p>
        <span data-ptag style="font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.14em;line-height:1;color:var(--stone)">STRUCTURE</span>
      </div>
      <div class="v3-reveal" data-prow style="display:grid;align-items:baseline;padding:26px 0;border-bottom:1px solid var(--line)">
        <span style="font-family:'IBM Plex Mono',monospace;font-size:11px;letter-spacing:.12em;line-height:1;color:var(--mosstext)">02</span>
        <p style="margin:0;font-size:var(--body);line-height:1.55;color:var(--fg);max-width:46ch">Conversion tracking is incomplete, so optimisation is flying blind.</p>
        <span data-ptag style="font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.14em;line-height:1;color:var(--stone)">TRACKING</span>
      </div>
      <div class="v3-reveal" data-prow style="display:grid;align-items:baseline;padding:26px 0;border-bottom:1px solid var(--line)">
        <span style="font-family:'IBM Plex Mono',monospace;font-size:11px;letter-spacing:.12em;line-height:1;color:var(--mosstext)">03</span>
        <p style="margin:0;font-size:var(--body);line-height:1.55;color:var(--fg);max-width:46ch">Audiences and creative aren't set up to learn over time.</p>
        <span data-ptag style="font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.14em;line-height:1;color:var(--stone)">LEARNING</span>
      </div>
      <div class="v3-reveal" data-prow style="display:grid;align-items:baseline;padding:26px 0;border-bottom:1px solid var(--line)">
        <span style="font-family:'IBM Plex Mono',monospace;font-size:11px;letter-spacing:.12em;line-height:1;color:var(--mosstext)">04</span>
        <p style="margin:0;font-size:var(--body);line-height:1.55;color:var(--fg);max-width:46ch">Reporting doesn't connect spend to revenue.</p>
        <span data-ptag style="font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.14em;line-height:1;color:var(--stone)">REPORTING</span>
      </div>
      <div class="v3-reveal" data-prow style="display:grid;align-items:baseline;padding:26px 0;border-bottom:1px solid var(--line)">
        <span style="font-family:'IBM Plex Mono',monospace;font-size:11px;letter-spacing:.12em;line-height:1;color:var(--mosstext)">05</span>
        <p style="margin:0;font-size:var(--body);line-height:1.55;color:var(--fg);max-width:46ch">Budget is spread thin instead of backing what works.</p>
        <span data-ptag style="font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.14em;line-height:1;color:var(--stone)">ALLOCATION</span>
      </div>
    </div>
  </section>

  <section id="loop" data-depth-label="DISTRIBUTION" style="padding:var(--sy) var(--pad) var(--sy)">
    <div class="v3-reveal" style="font-family:'IBM Plex Mono',monospace;font-size:11.5px;letter-spacing:.16em;line-height:1;color:var(--mosstext);margin-bottom:22px">COMPOUNDING LOOP</div>
    <div class="v3-reveal" data-cl-head style="display:grid;border-bottom:1px solid var(--line);padding-bottom:24px">
      <h2 data-h2 data-fit style="margin:0;font-family:Syne,sans-serif;font-weight:700;font-size:var(--h2);line-height:1.02;letter-spacing:-.035em;text-transform:uppercase">Campaigns compound when every round teaches the next one.</h2>
      <p style="margin:0;font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.14em;line-height:1.7;color:var(--stone);max-width:30ch">EXECUTION OUT &middot; VERIFIED SIGNAL BACK</p>
    </div>

    <div data-cl style="margin-top:40px">
      <div data-cl-desktop>
        <div style="position:relative;width:100%">
          <svg viewBox="0 0 1000 300" preserveAspectRatio="xMidYMid meet" aria-hidden="true" focusable="false" style="width:100%;height:auto;display:block;overflow:visible">
            <g>
              <path data-rail data-k="out" d="M180,105 H880"></path>
              <path data-rail data-k="fold" d="M880,105 Q930,105 930,145 V185 Q930,225 880,225"></path>
              <path data-rail data-k="ret" d="M880,225 H180"></path>
              <path data-rail data-k="rise" d="M180,225 Q130,225 130,185 V145 Q130,105 180,105"></path>
              <path data-chev d="M344,99 L352,105 L344,111"></path>
              <path data-chev d="M664,99 L672,105 L664,111"></path>
              <path data-chev d="M688,219 L680,225 L688,231"></path>
              <path data-chev d="M368,219 L360,225 L368,231"></path>
              <path data-fan data-k="fan" d="M800,112 L730,150"></path>
              <path data-fan data-k="fan" d="M800,112 L800,150"></path>
              <path data-fan data-k="fan" d="M800,112 L872,150"></path>
              <path data-trace data-k="trace" pathLength="1" d="M800,225 H180 Q130,225 130,185 V145 Q130,105 180,105 H240"></path>
            </g>
            <g>
              <circle data-node data-k="structure" cx="240" cy="105" r="5"></circle>
              <circle data-node data-k="launch" cx="520" cy="105" r="5"></circle>
              <circle data-node data-k="execution" cx="800" cy="105" r="6.5"></circle>
              <circle data-node data-k="signal" cx="800" cy="225" r="6.5"></circle>
              <circle data-node data-k="learn" cx="520" cy="225" r="5"></circle>
              <circle data-node data-k="reallocate" cx="240" cy="225" r="5"></circle>
              <circle data-node data-k="nexttest" cx="130" cy="165" r="5"></circle>
            </g>
            <g style="font-family:'IBM Plex Mono',monospace;font-size:13px;letter-spacing:1.5px">
              <text data-lab data-k="structure" x="240" y="85" text-anchor="middle">STRUCTURE</text>
              <text data-lab data-k="launch" x="520" y="85" text-anchor="middle">LAUNCH</text>
              <text data-lab data-k="execution" x="800" y="85" text-anchor="middle">EXECUTION</text>
              <text data-lab data-k="signal" x="800" y="252" text-anchor="middle">SIGNAL</text>
              <text data-lab data-k="learn" x="520" y="252" text-anchor="middle">LEARN</text>
              <text data-lab data-k="reallocate" x="240" y="252" text-anchor="middle">REALLOCATE</text>
              <text data-lab data-k="nexttest" x="112" y="169" text-anchor="end">NEXT TEST</text>
            </g>
            <g style="font-family:'IBM Plex Mono',monospace;font-size:11.5px;letter-spacing:1.2px">
              <text data-plat data-k="plat" x="730" y="167" text-anchor="middle">GOOGLE</text>
              <text data-plat data-k="plat" x="800" y="167" text-anchor="middle">META</text>
              <text data-plat data-k="plat" x="872" y="167" text-anchor="middle">LINKEDIN</text>
            </g>
          </svg>

          <div data-cl-cap-inner style="position:absolute;left:19%;top:41%;width:35%">
            <p style="margin:0;font-family:'IBM Plex Mono',monospace;font-size:10px;letter-spacing:.12em;line-height:1.6;color:var(--mosstext)">THE RETURN PATH IS THE ONE THAT COMPOUNDS</p>
            <p style="margin:12px 0 0;font-size:14.5px;line-height:1.6;color:var(--stone)">Structure, audiences and creative go out across the channels. What comes back is a verified conversion signal — and that signal is what the next test is built on.</p>
          </div>
        </div>
      </div>

      <div data-cl-mobile>
        <div data-mnext data-k="nexttest" style="display:flex;align-items:center;gap:10px;font-family:'IBM Plex Mono',monospace;font-size:11px;letter-spacing:.14em;line-height:1;margin-bottom:16px"><span aria-hidden="true">&uarr;</span>NEXT TEST &middot; SIGNAL CARRIED FORWARD</div>
        <div style="position:relative;padding-left:56px">
          <div data-mret data-k="trace" style="position:absolute;left:4px;top:6px;bottom:8px;width:30px;border-radius:14px 0 0 14px"></div>
          <div style="display:flex;align-items:center;gap:14px"><span data-mdot data-k="structure" style="width:10px;height:10px;border-radius:50%;flex:0 0 auto;display:block"></span><span data-mlab data-k="structure" style="font-family:'IBM Plex Mono',monospace;font-size:12px;letter-spacing:.14em;line-height:1">STRUCTURE</span></div>
          <div style="padding:8px 0"><span data-mseg data-k="out" style="width:2px;height:38px;margin-left:4px;flex:0 0 auto;display:block"></span></div>
          <div style="display:flex;align-items:center;gap:14px"><span data-mdot data-k="launch" style="width:10px;height:10px;border-radius:50%;flex:0 0 auto;display:block"></span><span data-mlab data-k="launch" style="font-family:'IBM Plex Mono',monospace;font-size:12px;letter-spacing:.14em;line-height:1">LAUNCH</span></div>
          <div style="padding:8px 0"><span data-mseg data-k="out" style="width:2px;height:38px;margin-left:4px;flex:0 0 auto;display:block"></span></div>
          <div style="display:flex;align-items:center;gap:14px"><span data-mdot data-k="execution" style="width:14px;height:14px;border-radius:50%;flex:0 0 auto;margin-left:-2px;display:block"></span><span data-mlab data-k="execution" style="font-family:'IBM Plex Mono',monospace;font-size:12px;letter-spacing:.14em;line-height:1">EXECUTION</span></div>
          <div style="display:flex;flex-wrap:wrap;gap:8px;padding:14px 0 6px;margin-left:18px">
            <span data-mchip data-k="plat" style="border-radius:2px;padding:7px 11px;font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.12em;line-height:1">GOOGLE</span>
            <span data-mchip data-k="plat" style="border-radius:2px;padding:7px 11px;font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.12em;line-height:1">META</span>
            <span data-mchip data-k="plat" style="border-radius:2px;padding:7px 11px;font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.12em;line-height:1">LINKEDIN</span>
          </div>
          <div style="padding:6px 0 8px"><span data-mseg data-k="fold" style="width:2px;height:38px;margin-left:4px;flex:0 0 auto;display:block"></span></div>
          <div style="display:flex;align-items:center;gap:14px"><span data-mdot data-k="signal" style="width:14px;height:14px;border-radius:50%;flex:0 0 auto;margin-left:-2px;display:block"></span><span data-mlab data-k="signal" style="font-family:'IBM Plex Mono',monospace;font-size:12px;letter-spacing:.14em;line-height:1">SIGNAL</span></div>
          <div style="padding:8px 0"><span data-mseg data-k="ret" style="width:2px;height:38px;margin-left:4px;flex:0 0 auto;display:block"></span></div>
          <div style="display:flex;align-items:center;gap:14px"><span data-mdot data-k="learn" style="width:10px;height:10px;border-radius:50%;flex:0 0 auto;display:block"></span><span data-mlab data-k="learn" style="font-family:'IBM Plex Mono',monospace;font-size:12px;letter-spacing:.14em;line-height:1">LEARN</span></div>
          <div style="padding:8px 0"><span data-mseg data-k="ret" style="width:2px;height:38px;margin-left:4px;flex:0 0 auto;display:block"></span></div>
          <div style="display:flex;align-items:center;gap:14px"><span data-mdot data-k="reallocate" style="width:10px;height:10px;border-radius:50%;flex:0 0 auto;display:block"></span><span data-mlab data-k="reallocate" style="font-family:'IBM Plex Mono',monospace;font-size:12px;letter-spacing:.14em;line-height:1">REALLOCATE</span></div>
        </div>
      </div>

      <div data-cl-cap-below>
        <p style="margin:0;font-family:'IBM Plex Mono',monospace;font-size:10px;letter-spacing:.12em;line-height:1.6;color:var(--mosstext)">THE RETURN PATH IS THE ONE THAT COMPOUNDS</p>
        <p style="margin:12px 0 0;font-size:15.5px;line-height:1.62;color:var(--stone);max-width:62ch">Structure, audiences and creative go out across the channels. What comes back is a verified conversion signal — and that signal is what the next test is built on. Campaigns that only keep running never close that loop.</p>
      </div>
      <p style="margin:26px 0 0;font-family:'IBM Plex Mono',monospace;font-size:10px;letter-spacing:.12em;line-height:1.6;color:var(--foot)">STRUCTURAL MODEL OF A CAMPAIGN OPERATING CYCLE &mdash; NOT A REPORTING VIEW</p>
    </div>
  </section>

  <section id="system" data-depth-label="SYSTEM" style="padding:0 var(--pad) var(--sy)">
    <div class="v3-reveal" style="font-family:'IBM Plex Mono',monospace;font-size:11.5px;letter-spacing:.16em;line-height:1;color:var(--mosstext);margin-bottom:22px">SERVICE ARCHITECTURE</div>
    <h2 class="v3-reveal" data-h2 data-fit style="margin:0;font-family:Syne,sans-serif;font-weight:700;font-size:var(--h2);line-height:1.02;letter-spacing:-.035em;text-transform:uppercase">How this connects to the wider system</h2>
    <p class="v3-reveal" style="margin:26px 0 0;font-size:var(--body);line-height:1.62;color:var(--stone);max-width:68ch">Paid media is the execution layer: campaign structure, audiences, creative, budget management and platform optimisation across Google, Meta and LinkedIn. It performs best inside a wider system — strategy, tracking, attribution, funnel analysis, conversion and reporting — which is where <a href="/services/performance-marketing/" style="color:var(--fg);border-bottom:1px solid var(--line2);padding-bottom:1px">Performance Marketing</a> connects the channel work to business outcomes.</p>

    <div class="v3-reveal" data-relpair style="display:grid;margin-top:44px;border-top:1px solid var(--line)">
      <div style="padding:26px 0 24px">
        <div style="font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.14em;line-height:1;color:var(--mosstext)">THIS SERVICE</div>
        <div style="font-family:Syne,sans-serif;font-weight:700;font-size:26px;letter-spacing:-.03em;line-height:1.05;text-transform:uppercase;margin-top:14px">Paid Media</div>
        <div style="font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.14em;line-height:1;color:var(--stone);margin-top:14px">EXECUTION LAYER</div>
      </div>
      <div data-relconn style="display:flex;align-items:center;justify-content:center;padding:0 0 24px">
        <span aria-hidden="true" style="font-family:'IBM Plex Mono',monospace;font-size:16px;line-height:1;color:var(--stone)">&updownarrow;</span>
      </div>
      <a data-relb href="/services/performance-marketing/" style="display:block;padding:26px 0 24px">
        <div style="font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.14em;line-height:1;color:var(--stone)">SITS INSIDE</div>
        <div style="display:flex;justify-content:space-between;align-items:baseline;gap:16px;font-family:Syne,sans-serif;font-weight:700;font-size:26px;letter-spacing:-.03em;line-height:1.05;text-transform:uppercase;margin-top:14px">Performance Marketing <span aria-hidden="true" style="color:var(--mosstext)">&rarr;</span></div>
        <div style="font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.14em;line-height:1;color:var(--stone);margin-top:14px">WIDER SYSTEM</div>
      </a>
    </div>
  </section>

  <section id="approach" data-depth-label="MID" style="background:var(--ibg);color:var(--ifg);padding:var(--sy) var(--pad)">
    <div class="v3-reveal" style="font-family:'IBM Plex Mono',monospace;font-size:11.5px;letter-spacing:.16em;line-height:1;color:var(--imut);margin-bottom:22px">THE APPROACH</div>
    <div class="v3-reveal" data-app-head style="display:grid;border-bottom:1px solid var(--iline);padding-bottom:28px;margin-bottom:32px">
      <h2 data-h2 data-fit style="margin:0;font-family:Syne,sans-serif;font-weight:700;font-size:var(--h2);line-height:1.02;letter-spacing:-.035em;text-transform:uppercase">Campaigns wired to real results.</h2>
      <p style="margin:0;font-size:var(--body);line-height:1.62;color:var(--ibody);max-width:56ch">We rebuild the foundations — tracking, structure and audiences — then run campaigns and creative tests that scale against verified conversions.</p>
    </div>

    <div data-cap-grid style="display:grid;gap:11px">
      <div data-cap style="background:var(--itile);border:1px solid var(--iline);border-radius:8px;box-shadow:var(--iedge);padding:26px 24px 28px">
        <span style="font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.14em;line-height:1;color:var(--imut)">01</span>
        <h3 data-cap-h style="margin:14px 0 0;font-family:Syne,sans-serif;font-weight:700;font-size:var(--h3);line-height:1.18;letter-spacing:-.02em">Paid search</h3>
        <p style="margin:12px 0 0;font-size:var(--card);line-height:1.62;color:var(--ibody)">Google Ads structured for intent, with conversion tracking that reflects real revenue.</p>
      </div>
      <div data-cap style="background:var(--itile);border:1px solid var(--iline);border-radius:8px;box-shadow:var(--iedge);padding:26px 24px 28px">
        <span style="font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.14em;line-height:1;color:var(--imut)">02</span>
        <h3 data-cap-h style="margin:14px 0 0;font-family:Syne,sans-serif;font-weight:700;font-size:var(--h3);line-height:1.18;letter-spacing:-.02em">Paid social</h3>
        <p style="margin:12px 0 0;font-size:var(--card);line-height:1.62;color:var(--ibody)">Meta and LinkedIn campaigns built to test, learn and scale efficiently.</p>
      </div>
      <div data-cap style="background:var(--itile);border:1px solid var(--iline);border-radius:8px;box-shadow:var(--iedge);padding:26px 24px 28px">
        <span style="font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.14em;line-height:1;color:var(--imut)">03</span>
        <h3 data-cap-h style="margin:14px 0 0;font-family:Syne,sans-serif;font-weight:700;font-size:var(--h3);line-height:1.18;letter-spacing:-.02em">Audience strategy</h3>
        <p style="margin:12px 0 0;font-size:var(--card);line-height:1.62;color:var(--ibody)">Targeting and retargeting designed around the buyer, not platform defaults.</p>
      </div>
      <div data-cap style="background:var(--itile);border:1px solid var(--iline);border-radius:8px;box-shadow:var(--iedge);padding:26px 24px 28px">
        <span style="font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.14em;line-height:1;color:var(--imut)">04</span>
        <h3 data-cap-h style="margin:14px 0 0;font-family:Syne,sans-serif;font-weight:700;font-size:var(--h3);line-height:1.18;letter-spacing:-.02em">Conversion tracking</h3>
        <p style="margin:12px 0 0;font-size:var(--card);line-height:1.62;color:var(--ibody)">Events and tracking rebuilt so optimisation is based on outcomes that matter.</p>
      </div>
      <div data-cap style="background:var(--itile);border:1px solid var(--iline);border-radius:8px;box-shadow:var(--iedge);padding:26px 24px 28px">
        <span style="font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.14em;line-height:1;color:var(--imut)">05</span>
        <h3 data-cap-h style="margin:14px 0 0;font-family:Syne,sans-serif;font-weight:700;font-size:var(--h3);line-height:1.18;letter-spacing:-.02em">Creative testing</h3>
        <p style="margin:12px 0 0;font-size:var(--card);line-height:1.62;color:var(--ibody)">A structured testing cadence so creative improves on evidence.</p>
      </div>
      <div data-cap style="background:var(--itile);border:1px solid var(--iline);border-radius:8px;box-shadow:var(--iedge);padding:26px 24px 28px">
        <span style="font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.14em;line-height:1;color:var(--imut)">06</span>
        <h3 data-cap-h style="margin:14px 0 0;font-family:Syne,sans-serif;font-weight:700;font-size:var(--h3);line-height:1.18;letter-spacing:-.02em">Budget optimisation &amp; reporting</h3>
        <p style="margin:12px 0 0;font-size:var(--card);line-height:1.62;color:var(--ibody)">Continuous reallocation toward return, with reporting tied to the business.</p>
      </div>
    </div>
  </section>

  <section id="deliverables" data-depth-label="OUTPUT" style="padding:var(--sy) var(--pad) var(--sy)">
    <div class="v3-reveal" style="font-family:'IBM Plex Mono',monospace;font-size:11.5px;letter-spacing:.16em;line-height:1;color:var(--mosstext);margin-bottom:22px">WHAT YOU GET</div>
    <h2 class="v3-reveal" data-h2 data-fit style="margin:0 0 40px;font-family:Syne,sans-serif;font-weight:700;font-size:var(--h2);line-height:1.02;letter-spacing:-.035em;text-transform:uppercase">Deliverables that make growth measurable.</h2>

    <div data-dgrid style="display:grid;gap:0 40px;border-top:1px solid var(--line)">
      <div class="v3-reveal" style="display:grid;grid-template-columns:44px minmax(0,1fr);gap:0 16px;align-items:baseline;padding:20px 0;border-bottom:1px solid var(--line)"><span style="font-family:'IBM Plex Mono',monospace;font-size:11px;letter-spacing:.12em;line-height:1;color:var(--mosstext)">01</span><span data-dname style="font-family:Syne,sans-serif;font-weight:700;letter-spacing:-.03em;line-height:1.1;text-transform:uppercase">Account audit</span></div>
      <div class="v3-reveal" style="display:grid;grid-template-columns:44px minmax(0,1fr);gap:0 16px;align-items:baseline;padding:20px 0;border-bottom:1px solid var(--line)"><span style="font-family:'IBM Plex Mono',monospace;font-size:11px;letter-spacing:.12em;line-height:1;color:var(--mosstext)">02</span><span data-dname style="font-family:Syne,sans-serif;font-weight:700;letter-spacing:-.03em;line-height:1.1;text-transform:uppercase">Tracking rebuild</span></div>
      <div class="v3-reveal" style="display:grid;grid-template-columns:44px minmax(0,1fr);gap:0 16px;align-items:baseline;padding:20px 0;border-bottom:1px solid var(--line)"><span style="font-family:'IBM Plex Mono',monospace;font-size:11px;letter-spacing:.12em;line-height:1;color:var(--mosstext)">03</span><span data-dname style="font-family:Syne,sans-serif;font-weight:700;letter-spacing:-.03em;line-height:1.1;text-transform:uppercase">Campaign structure</span></div>
      <div class="v3-reveal" style="display:grid;grid-template-columns:44px minmax(0,1fr);gap:0 16px;align-items:baseline;padding:20px 0;border-bottom:1px solid var(--line)"><span style="font-family:'IBM Plex Mono',monospace;font-size:11px;letter-spacing:.12em;line-height:1;color:var(--mosstext)">04</span><span data-dname style="font-family:Syne,sans-serif;font-weight:700;letter-spacing:-.03em;line-height:1.1;text-transform:uppercase">Audience plan</span></div>
      <div class="v3-reveal" style="display:grid;grid-template-columns:44px minmax(0,1fr);gap:0 16px;align-items:baseline;padding:20px 0;border-bottom:1px solid var(--line)"><span style="font-family:'IBM Plex Mono',monospace;font-size:11px;letter-spacing:.12em;line-height:1;color:var(--mosstext)">05</span><span data-dname style="font-family:Syne,sans-serif;font-weight:700;letter-spacing:-.03em;line-height:1.1;text-transform:uppercase">Creative testing plan</span></div>
      <div class="v3-reveal" style="display:grid;grid-template-columns:44px minmax(0,1fr);gap:0 16px;align-items:baseline;padding:20px 0;border-bottom:1px solid var(--line)"><span style="font-family:'IBM Plex Mono',monospace;font-size:11px;letter-spacing:.12em;line-height:1;color:var(--mosstext)">06</span><span data-dname style="font-family:Syne,sans-serif;font-weight:700;letter-spacing:-.03em;line-height:1.1;text-transform:uppercase">Reporting</span></div>
    </div>

    <div data-proof-grid style="display:grid;gap:40px">
      <article class="v3-reveal" data-proof style="display:flex;flex-direction:column;padding:0 0 8px">
        <div data-proof-l style="font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.14em;line-height:1.5;color:var(--mosstext);padding-bottom:18px;border-bottom:1px solid var(--line)">EDTECH GROWTH ENGAGEMENT</div>
        <ul data-proof-m style="list-style:none;margin:0;padding:0;display:flex;flex-direction:column">
          <li style="font-family:Syne,sans-serif;font-weight:600;font-size:20px;letter-spacing:-.02em;line-height:1.3;padding:16px 0;border-bottom:1px solid var(--line)">Monthly media spend scaled &#8377;5L &rarr; &#8377;30L</li>
          <li style="font-family:Syne,sans-serif;font-weight:600;font-size:20px;letter-spacing:-.02em;line-height:1.3;padding:16px 0;border-bottom:1px solid var(--line)">Monthly revenue reached &#8377;1.5 crore</li>
          <li style="font-family:Syne,sans-serif;font-weight:600;font-size:20px;letter-spacing:-.02em;line-height:1.3;padding:16px 0;border-bottom:1px solid var(--line)">5&times; return on ad spend</li>
        </ul>
        <p data-proof-s style="margin:20px 0 0;font-size:15.5px;line-height:1.62;color:var(--stone)">Rebuilt tracking and conversion events, then scaled paid media against verified return.</p>
      </article>
      <article class="v3-reveal" data-proof style="display:flex;flex-direction:column;padding:0 0 8px">
        <div data-proof-l style="font-family:'IBM Plex Mono',monospace;font-size:10.5px;letter-spacing:.14em;line-height:1.5;color:var(--mosstext);padding-bottom:18px;border-bottom:1px solid var(--line)">CRYPTO AFFILIATE GROWTH ENGAGEMENT</div>
        <ul data-proof-m style="list-style:none;margin:0;padding:0;display:flex;flex-direction:column">
          <li style="font-family:Syne,sans-serif;font-weight:600;font-size:20px;letter-spacing:-.02em;line-height:1.3;padding:16px 0;border-bottom:1px solid var(--line)">Affiliate contribution grew from ~0%</li>
          <li style="font-family:Syne,sans-serif;font-weight:600;font-size:20px;letter-spacing:-.02em;line-height:1.3;padding:16px 0;border-bottom:1px solid var(--line)">Reached ~5&ndash;6% of total trading volume within one year</li>
        </ul>
        <p data-proof-s style="margin:20px 0 0;font-size:15.5px;line-height:1.62;color:var(--stone)">Built the affiliate program from scratch — partner validation, commercial model and tracking.</p>
      </article>
    </div>
    <p style="margin:26px 0 0;font-family:'IBM Plex Mono',monospace;font-size:10px;letter-spacing:.12em;line-height:1.6;color:var(--foot)">GENERAL GROWTH EVIDENCE FROM THE FOUNDER AND CORE TEAM</p>
  </section>

  <section id="faq" data-depth-label="QUESTIONS" style="background:var(--ibg);color:var(--ifg);padding:var(--sy) var(--pad)">
    <div data-faq-grid style="display:grid;align-items:start">
      <div class="v3-reveal">
        <div style="font-family:'IBM Plex Mono',monospace;font-size:11.5px;letter-spacing:.16em;line-height:1;color:var(--imut);margin-bottom:22px">QUESTIONS</div>
        <h2 data-h2 data-fit style="margin:0;font-family:Syne,sans-serif;font-weight:700;font-size:var(--h2);line-height:1.02;letter-spacing:-.035em;text-transform:uppercase">Paid Media, answered.</h2>
        <p style="margin:30px 0 0;font-size:15.5px;line-height:1.75;color:var(--ibody);max-width:40ch">Related services: <a href="/services/performance-marketing/" style="border-bottom:1px solid var(--ichip);padding-bottom:1px">Performance Marketing</a> · <a href="/services/brand-creative/" style="border-bottom:1px solid var(--ichip);padding-bottom:1px">Brand Strategy &amp; Performance Creative</a> · <a href="/services/growth-strategy-measurement/" style="border-bottom:1px solid var(--ichip);padding-bottom:1px">Growth Strategy &amp; Measurement</a></p>
      </div>

      <div>
        <div style="border-top:1px solid var(--iline)">
          <h3 style="margin:0"><button data-faq-btn="0" id="faq-b0" aria-controls="faq-p0" aria-expanded="true" style="width:100%;display:flex;justify-content:space-between;align-items:flex-start;gap:24px;text-align:left;background:transparent;border:0;padding:26px 0;font-family:Syne,sans-serif;font-weight:700;font-size:20px;line-height:1.3;letter-spacing:-.02em;color:var(--ifg);cursor:pointer"><span>Which platforms do you run?</span><span data-faq-ic="0" aria-hidden="true" style="flex:0 0 auto;font-family:'IBM Plex Mono',monospace;font-weight:400;font-size:22px;line-height:1;color:var(--imut)">+</span></button></h3>
          <div data-faq-ans="0" id="faq-p0" role="region" aria-labelledby="faq-b0">
            <p style="margin:0;padding:0 0 28px;font-size:16.5px;line-height:1.7;color:var(--ibody);max-width:62ch">Primarily Google, Meta and LinkedIn — paid search and paid social. We recommend the mix based on where your buyers actually are, not on what we prefer to run.</p>
          </div>
        </div>
        <div style="border-top:1px solid var(--iline)">
          <h3 style="margin:0"><button data-faq-btn="1" id="faq-b1" aria-controls="faq-p1" aria-expanded="false" style="width:100%;display:flex;justify-content:space-between;align-items:flex-start;gap:24px;text-align:left;background:transparent;border:0;padding:26px 0;font-family:Syne,sans-serif;font-weight:700;font-size:20px;line-height:1.3;letter-spacing:-.02em;color:var(--ifg);cursor:pointer"><span>Can you audit our existing accounts first?</span><span data-faq-ic="1" aria-hidden="true" style="flex:0 0 auto;font-family:'IBM Plex Mono',monospace;font-weight:400;font-size:22px;line-height:1;color:var(--imut)">+</span></button></h3>
          <div data-faq-ans="1" id="faq-p1" role="region" aria-labelledby="faq-b1">
            <p style="margin:0;padding:0 0 28px;font-size:16.5px;line-height:1.7;color:var(--ibody);max-width:62ch">Yes. A paid-media audit before increasing budget is usually the smartest first step — it shows where spend is leaking and what to fix before scaling.</p>
          </div>
        </div>
        <div style="border-top:1px solid var(--iline);border-bottom:1px solid var(--iline)">
          <h3 style="margin:0"><button data-faq-btn="2" id="faq-b2" aria-controls="faq-p2" aria-expanded="false" style="width:100%;display:flex;justify-content:space-between;align-items:flex-start;gap:24px;text-align:left;background:transparent;border:0;padding:26px 0;font-family:Syne,sans-serif;font-weight:700;font-size:20px;line-height:1.3;letter-spacing:-.02em;color:var(--ifg);cursor:pointer"><span>Do you handle creative too?</span><span data-faq-ic="2" aria-hidden="true" style="flex:0 0 auto;font-family:'IBM Plex Mono',monospace;font-weight:400;font-size:22px;line-height:1;color:var(--imut)">+</span></button></h3>
          <div data-faq-ans="2" id="faq-p2" role="region" aria-labelledby="faq-b2">
            <p style="margin:0;padding:0 0 28px;font-size:16.5px;line-height:1.7;color:var(--ibody);max-width:62ch">We coordinate and test creative, and can produce performance creative through our brand and creative capability where needed.</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section id="cta" data-depth-label="NEXT" style="background:var(--moss);color:#101310;padding:var(--sy) var(--pad)">
    <div style="font-family:'IBM Plex Mono',monospace;font-size:11.5px;letter-spacing:.16em;line-height:1;color:rgba(16,19,16,.6);margin-bottom:24px">NEXT STEP</div>
    <div data-cta-grid style="display:grid">
      <h2 data-cta-h data-fit style="margin:0;font-family:Syne,sans-serif;font-weight:800;line-height:.94;letter-spacing:-.04em;text-transform:uppercase">Ready to work on <span style="color:rgba(16,19,16,.62)">paid media</span>?</h2>
      <div>
        <p style="margin:0;font-size:var(--body);line-height:1.6;color:rgba(16,19,16,.78);max-width:46ch">Tell us where you are and what you're trying to grow. We'll review the foundations before recommending the work.</p>
        <div data-cta-actions style="display:flex;margin-top:34px">
          <a data-ctacta href="/contact/" style="display:inline-flex;align-items:center;justify-content:center;gap:10px;height:54px;padding:0 28px;background:#101310;color:#F3F5F1;font-family:Syne,sans-serif;font-weight:700;font-size:14.5px;text-transform:uppercase;line-height:1;white-space:nowrap;border-radius:2px">Discuss Your Growth Project <span aria-hidden="true">&rarr;</span></a>
          <a data-ctatext href="/contact/" data-secondary style="display:inline-flex;align-items:center;height:54px;font-size:14.5px;line-height:1;white-space:nowrap;color:rgba(16,19,16,.72)"><span style="border-bottom:1px solid rgba(16,19,16,.4);padding-bottom:3px">Request a Foundation Audit &rarr;</span></a>
        </div>
      </div>
    </div>
  </section>
`;

export default {
  path,
  shell: "v3",
  // v3-paid carries this page's own type ladders, the stacked-at-all-widths
  // hero, the service-architecture row and the COMPOUNDING LOOP, layered over
  // the shared service-detail system without touching it.
  shellClass: "v3-service-detail v3-paid",
  navCta: "Discuss a Project",
  footRule: true,
  headExtra: `<link rel="stylesheet" href="/assets/service-detail.css">
<link rel="stylesheet" href="/assets/service-detail-paid.css">`,
  bodyScripts: ["/service-detail.js"],
  title: "Paid Media Agency — Google, Meta & LinkedIn Ads | Tilth",
  description: svc.summary,
  ogTitle: svc.name,
  ogDescription: svc.summary,
  schema: [serviceSchema, bc.schema, faqSchema],
  main
};
